#!/usr/bin/env bash
# Configures /etc/hosts so localhost resolves to 127.0.0.2 and facebook.com to 8.8.8.8

TMP_FILE=$(mktemp)

grep -vE 'localhost|facebook\.com' /etc/hosts > "$TMP_FILE"

echo "127.0.0.2 localhost" >> "$TMP_FILE"
echo "8.8.8.8 facebook.com" >> "$TMP_FILE"

cat "$TMP_FILE" > /etc/hosts

rm "$TMP_FILE"
